name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install --save-dev http-server puppeteer
        
    - name: Start HTTP server
      run: npx http-server -p 8080 &
      
    - name: Wait for server to start
      run: sleep 5
      
    - name: Run tests with Puppeteer
      run: |
        node .github/workflows/run-tests.js
